require 'rails_helper'

RSpec.describe CollectionSpace::Converter::Materials::MaterialsMaterial do
  let(:attributes) { get_attributes('materials', 'materials_authority.csv') }
  let(:materialsmaterial) { MaterialsMaterial.new(attributes) }
  let(:doc) { get_doc(materialsmaterial) }
  let(:record) { get_fixture('materials_authority.xml') }
  let(:xpaths) {[
    "/document/*/materialTermGroupList/materialTermGroup/termDisplayName",
    "/document/*/materialTermGroupList/materialTermGroup/termName",
    "/document/*/materialTermGroupList/materialTermGroup/termQualifier",
    "/document/*/materialTermGroupList/materialTermGroup/termStatus",
    "/document/*/materialTermGroupList/materialTermGroup/termType",
    { xpath: '/document/*/materialTermGroupList/materialTermGroup/termFlag', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    "/document/*/materialTermGroupList/materialTermGroup/historicalStatus",
    { xpath: '/document/*/materialTermGroupList/materialTermGroup/termLanguage', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    "/document/*/materialTermGroupList/materialTermGroup/termPrefForLang",
    { xpath: '/document/*/materialTermGroupList/materialTermGroup/termSource', transform: ->(text) { CSURN.parse(text)[:label] } },
    "/document/*/materialTermGroupList/materialTermGroup/termSourceDetail",
    "/document/*/materialTermGroupList/materialTermGroup/termSourceID",
    "/document/*/materialTermGroupList/materialTermGroup/termSourceNote",
    { xpath: '/document/*/publishToList/publishTo', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    { xpath: '/document/*/materialCompositionGroupList/materialCompositionGroup/materialCompositionFamilyName', transform: ->(text) { CSURN.parse(text)[:label] } },
    { xpath: '/document/*/materialCompositionGroupList/materialCompositionGroup/materialCompositionClassName', transform: ->(text) { CSURN.parse(text)[:label] } },
    { xpath: '/document/*/materialCompositionGroupList/materialCompositionGroup/materialCompositionGenericName', transform: ->(text) { CSURN.parse(text)[:label] } },
    "/document/*/description",
    { xpath: '/document/*/typicalUses/typicalUse', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    "/document/*/discontinued",
    { xpath: '/document/*/discontinuedBy', transform: ->(text) { CSURN.parse(text)[:label] } },
    "/document/*/discontinuedDate",
    "/document/*/productionDate",
    "/document/*/productionNote",
    { xpath: '/document/*/materialProductionOrganizationGroupList/materialProductionOrganizationGroup/materialProductionOrganization', transform: ->(text) { CSURN.parse(text)[:label] } },
    { xpath: '/document/*/materialProductionOrganizationGroupList/materialProductionOrganizationGroup/materialProductionOrganizationRole', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    { xpath: '/document/*/materialProductionPersonGroupList/materialProductionPersonGroup/materialProductionPerson', transform: ->(text) { CSURN.parse(text)[:label] } },
    { xpath: '/document/*/materialProductionPersonGroupList/materialProductionPersonGroup/materialProductionPersonRole', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    { xpath: '/document/*/materialProductionPlaceGroupList/materialProductionPlaceGroup/materialProductionPlace', transform: ->(text) { CSURN.parse(text)[:label] } },
    { xpath: '/document/*/materialProductionPlaceGroupList/materialProductionPlaceGroup/materialProductionPlaceRole', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    { xpath: '/document/*/featuredApplicationGroupList/featuredApplicationGroup/featuredApplication', transform: ->(text) { CSURN.parse(text)[:label] } },
    "/document/*/featuredApplicationGroupList/featuredApplicationGroup/featuredApplicationNote",
    { xpath: '/document/*/materialCitationGroupList/materialCitationGroup/materialCitationSource', transform: ->(text) { CSURN.parse(text)[:label] } },
    "/document/*/materialCitationGroupList/materialCitationGroup/materialCitationSourceDetail",
    "/document/*/externalUrlGroupList/externalUrlGroup/externalUrl",
    "/document/*/externalUrlGroupList/externalUrlGroup/externalUrlNote",
    { xpath: '/document/*/additionalResourceGroupList/additionalResourceGroup/additionalResource', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    "/document/*/additionalResourceGroupList/additionalResourceGroup/additionalResourceNote",
    { xpath: '/document/*/materialTermAttributionContributingGroupList/materialTermAttributionContributingGroup/materialTermAttributionContributingOrganization', transform: ->(text) { CSURN.parse(text)[:label] } },
    { xpath: '/document/*/materialTermAttributionContributingGroupList/materialTermAttributionContributingGroup/materialTermAttributionContributingPerson', transform: ->(text) { CSURN.parse(text)[:label] } },
    "/document/*/materialTermAttributionContributingGroupList/materialTermAttributionContributingGroup/materialTermAttributionContributingDate",
    { xpath: '/document/*/materialTermAttributionEditingGroupList/materialTermAttributionEditingGroup/materialTermAttributionEditingOrganization', transform: ->(text) { CSURN.parse(text)[:label] } },
    { xpath: '/document/*/materialTermAttributionEditingGroupList/materialTermAttributionEditingGroup/materialTermAttributionEditingPerson', transform: ->(text) { CSURN.parse(text)[:label] } },
    "/document/*/materialTermAttributionEditingGroupList/materialTermAttributionEditingGroup/materialTermAttributionEditingNote",
    "/document/*/materialTermAttributionEditingGroupList/materialTermAttributionEditingGroup/materialTermAttributionEditingDate",
    { xpath: '/document/*/commonForm', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    { xpath: '/document/*/formTypeGroupList/formTypeGroup/formType', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    "/document/*/typicalSizeGroupList/typicalSizeGroup/typicalSize",
    "/document/*/typicalSizeGroupList/typicalSizeGroup/typicalSize/typicalSizeDimensionGroupList/typicalSizeDimensionGroup/dimension",
    "/document/*/typicalSizeGroupList/typicalSizeGroup/typicalSize/typicalSizeDimensionGroupList/typicalSizeDimensionGroup/value",
    "/document/*/typicalSizeGroupList/typicalSizeGroup/typicalSize/typicalSizeDimensionGroupList/typicalSizeDimensionGroup/measurementUnit",
    "/document/*/formNote",
    { xpath: '/document/*/acousticalPropertyGroupList/acousticalPropertyGroup/acousticalPropertyType', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    "/document/*/acousticalPropertyGroupList/acousticalPropertyGroup/acousticalPropertyNote",
    { xpath: '/document/*/durabilityPropertyGroupList/durabilityPropertyGroup/durabilityPropertyType', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    "/document/*/durabilityPropertyGroupList/durabilityPropertyGroup/durabilityPropertyNote",
    { xpath: '/document/*/electricalPropertyGroupList/electricalPropertyGroup/electricalPropertyType', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    "/document/*/electricalPropertyGroupList/electricalPropertyGroup/electricalPropertyNote",
    { xpath: '/document/*/hygrothermalPropertyGroupList/hygrothermalPropertyGroup/hygrothermalPropertyType', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    "/document/*/hygrothermalPropertyGroupList/hygrothermalPropertyGroup/hygrothermalPropertyNote",
    { xpath: '/document/*/mechanicalPropertyGroupList/mechanicalPropertyGroup/mechanicalPropertyType', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    "/document/*/mechanicalPropertyGroupList/mechanicalPropertyGroup/mechanicalPropertyNote",
    { xpath: '/document/*/opticalPropertyGroupList/opticalPropertyGroup/opticalPropertyType', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    "/document/*/opticalPropertyGroupList/opticalPropertyGroup/opticalPropertyNote",
    { xpath: '/document/*/sensorialPropertyGroupList/sensorialPropertyGroup/sensorialPropertyType', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    "/document/*/sensorialPropertyGroupList/sensorialPropertyGroup/sensorialPropertyNote",
    { xpath: '/document/*/smartMaterialPropertyGroupList/smartMaterialPropertyGroup/smartMaterialPropertyType', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    "/document/*/smartMaterialPropertyGroupList/smartMaterialPropertyGroup/smartMaterialPropertyNote",
    { xpath: '/document/*/additionalPropertyGroupList/additionalPropertyGroup/additionalPropertyType', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    "/document/*/additionalPropertyGroupList/additionalPropertyGroup/additionalPropertyNote",
    "/document/*/propertyNote",
    "/document/*/recycledContentGroupList/recycledContentGroup/recycledContent",
    "/document/*/recycledContentGroupList/recycledContentGroup/recycledContentHigh",
    "/document/*/recycledContentGroupList/recycledContentGroup/recycledContentQualifier",
    { xpath: '/document/*/lifecycleComponentGroupList/lifecycleComponentGroup/lifecycleComponent', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    "/document/*/lifecycleComponentGroupList/lifecycleComponentGroup/lifecycleComponentNote",
    "/document/*/embodiedEnergyGroupList/embodiedEnergyGroup/embodiedEnergyValue",
    "/document/*/embodiedEnergyGroupList/embodiedEnergyGroup/embodiedEnergyValueHigh",
    { xpath: '/document/*/embodiedEnergyGroupList/embodiedEnergyGroup/embodiedEnergyUnit', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    "/document/*/embodiedEnergyGroupList/embodiedEnergyGroup/embodiedEnergyNote",
    { xpath: '/document/*/certificationCreditGroupList/certificationCreditGroup/certificationProgram', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    "/document/*/certificationCreditGroupList/certificationCreditGroup/certificationCreditNote",
    "/document/*/ecologyNote",
    { xpath: '/document/*/castingProcesses/castingProcess', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    { xpath: '/document/*/deformingProcesses/deformingProcess', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    { xpath: '/document/*/joiningProcesses/joiningProcess', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    { xpath: '/document/*/machiningProcesses/machiningProcess', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    { xpath: '/document/*/moldingProcesses/moldingProcess', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    { xpath: '/document/*/rapidPrototypingProcesses/rapidPrototypingProcess', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    { xpath: '/document/*/surfacingProcesses/surfacingProcess', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    { xpath: '/document/*/additionalProcessGroupList/additionalProcessGroup/additionalProcess', transform: ->(text) { CSURN.parse(text)[:label].downcase } },
    "/document/*/additionalProcessGroupList/additionalProcessGroup/additionalProcessNote",
    "/document/*/processNote",
  ]}

  it "Maps attributes correctly" do
    test_converter(doc, record, xpaths)
  end
end

